name: 'ioBroker Testing: check and lint'
author: 'AlCalzone'
description: 'Perform type checking, linting and testing of an ioBroker adapter package'

inputs:
  node-version:
    description: 'Node.js version'
    required: true
  install-command:
    description: "Overwrite the default install command"
    default: 'npm ci'
  package-cache:
    description: "Define which package manager to use for dependency caching. Set to 'false' to disable caching."
    default: 'npm'
  type-checking:
    description: 'Set to true when the adapter should be type-checked'
    default: 'false'
  type-checking-command:
    description: 'Overwrite the default type checking command'
    default: 'npm run check'
  lint:
    description: 'Set to true when the adapter has a linter configured'
    default: 'false'
  lint-command:
    description: 'Overwrite the default lint command'
    default: 'npm run lint'
  test-command:
    description: 'Overwrite the default test command'
    default: 'npm run test:package'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ (inputs.package-cache != 'false' && inputs.package-cache != '') && inputs.package-cache || '' }}

    - name: Install Dependencies
      shell: bash
      run: ${{ inputs.install-command }}

    - name: Perform a type check
      shell: bash
      run: |
        if ${{ inputs.type-checking }}; then
          ${{ inputs.type-checking-command }}
        else
          echo "Skipping type check..."
        fi

    - name: Lint source code
      shell: bash
      run: |
        if ${{ inputs.lint }}; then
          ${{ inputs.lint-command }}
        else
          echo "No linter configured, skipping..."
        fi

    - name: Test package files
      if: ${{ inputs.test-command != 'false' }}
      shell: bash
      run: "${{ inputs.test-command }}"
